### ISSUE TITLE
Suggestion for getting Brakeman working?

### ISSUE THREAD

**Issue by david-a-wheeler** [step-security/harden-runner#147]
Hi, I'm trying to add harden-runner to run on the OpenSSF Best Practices badge. The PR is here:

> https://github.com/coreinfrastructure/best-practices-badge/pull/1786

Everything is fine when it runs the test "run a one-line script" and "run a multi-line script". However, when it tries to run "Brakeman linter" I get this error:

> Error: The log was not found. It may have been deleted based on retention settings.

I'm not sure how to adjust the retention settings. Suggestions?
The relevant part of [.github/workflows/main.yml](https://github.com/coreinfrastructure/best-practices-badge/blob/harden-runner/.github/workflows/main.yml) is:

~~~~
     # Run Brakeman. See https://github.com/devmasx/brakeman-linter-action
      - name: Brakeman linter
        # To review release options see:
        # https://github.com/devmasx/brakeman-linter-action/releases
        uses: devmasx/brakeman-linter-action@0dc80fcccf87915ccb1761669014015214f36287 # pin@v1.0.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
~~~~

**Comment by varunsh-coder** [comment]
Hi @david-a-wheeler, thanks for trying it out!

Are you referring to this Action run: https://github.com/coreinfrastructure/best-practices-badge/runs/5558007085?check_suite_focus=true?

If so, the reason is says `log not found` is because it was run more than 3 months back. Github Actions only retains the logs for 90 days. I saw that all the workflow runs for the `harden-runner` branch are over 3 months old. 

If you run a workflow that has `harden-runner` GitHub Action now, it should show the logs. Also, note that the link to insights is in the `harden-runner` step. As an example, this link shows there the insights URL is for one of the Scorecard workflows: https://github.com/ossf/scorecard/runs/7113863225?check_suite_focus=true#step:3:11

**Comment by varunsh-coder** [comment]
Hi @david-a-wheeler please let me know if you have any follow up questions

**Comment by david-a-wheeler** [comment]
You're right! I was looking for something complex instead of the simple.

Thanks so much!!
