### ISSUE TITLE
Access denied on my own private repo

### ISSUE THREAD

**Issue by stefreak** [step-security/harden-runner#171]
When I try to look at the audit log of my own private repository, after installing the Harden Runner App,
I get the error message "Access Denied".

Maybe it's because we also have the Harden Runner App installed in the Garden org?

Example run: https://app.stepsecurity.io/github/stefreak/stepsecurity-experiments/actions/runs/2925641138

**Comment by varunsh-coder** [comment]
Thanks for reporting @stefreak! Let me investigate and get back ASAP.

**Comment by varunsh-coder** [comment]
I believe I have found the issue. We use this API to check authorization

https://docs.github.com/en/rest/apps/installations#list-repositories-accessible-to-the-user-access-token

and this only returns 30 repositories by default due to pagination. The bug is that we are not currently making additional calls to get the rest of the pages. Since you have more than 30 repositories, it is not finding this one. 

Let me get this addressed and get back to you. Sorry about that.

**Comment by varunsh-coder** [comment]
This issue has been resolved partially. It should work for you now. Please try it and let me know. 

Full fix will be released in a couple of days.

**Comment by stefreak** [comment]
No worries @varunsh-coder – thank you a lot for addressing this so quickly, I'm glad to have helped on finding this one!

**Comment by stefreak** [comment]
Thank you, it works
