### ISSUE TITLE
Allowed endpoint could not be resolved

### ISSUE THREAD

**Issue by ben-manes** [step-security/harden-runner#283]
> Thu, 20 Apr 2023 00:22:15 GMT:Error resolving allowed domain error in response from dns.google unable to resolve domain repo.maven.apache.org.
Thu, 20 Apr 2023 00:22:15 GMT:unable to resolve domain: repo.maven.apache.org.
Thu, 20 Apr 2023 00:22:15 GMT:Reverted changes
> Error: StepSecurity Harden Runner: Reverting agent since allowed endpoint repo.maven.apache.org could not be resolved

The domain is on the allow list and has worked in prior runs. It appears that Google's dns entry is not resolving, causing the workflow to fail. I can resolve it locally, but have not tried it through that dns. Can the runner be more resilient to a dns outage?

See [failed job](https://github.com/ben-manes/caffeine/actions/runs/4749119771/jobs/8436091995)

**Comment by ben-manes** [comment]
I'll close since this seems to have been broader and the dns fixed.

**Comment by varunsh-coder** [comment]
Hi @ben-manes, thanks for reporting the issue!

The current logic is that in `block` mode, harden-runner tries to resolve each of the allowed domains in the `pre` step. It reverts the agent (in the `pre` step) if it cannot resolve even one of them (maybe because the domain has a typo and is incorrect, or it cannot be resolved at that time). Once the agent is reverted (maybe `uninstalled` would be a better term), the hosted runner handles all DNS calls. So, in this case, the job did not fail because of harden runner. As you mentioned, there was probably a broader DNS issue. 

Please let me know if you have feedback on the current logic, and we can improve it.
