### ISSUE TITLE
allow-endpoints should accept wildcards or better handle Github artifact hosts

### ISSUE THREAD

**Issue by mjpieters** [step-security/harden-runner#83]
As [per the GitHub runner requirements](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners), a GitHub runner that needs to handle caches and artefacts should be able to connect to `*.blob.core.windows.net` hosts.

E.g. my [build workflow](https://github.com/mjpieters/SO-userscripts/blob/main/.github/workflows/build.yaml) connected to `kv4gacprodeus2file3.blob.core.windows.net:443`, to download the yarn cache, and then optionally would upload it again in a post step (via [`action/setup-node` action](https://github.com/actions/setup-node), which uses `actions/cache`).

The GH cache action uses an indirect API; an API call is made to `artifactcache.actions.githubusercontent.com` to get the blob location, which in my case was `kv4gacprodeus2file3.blob.core.windows.net`. However, there is no guarantee that a next run will use that same hostname!

My [next run](https://app.stepsecurity.io/github/mjpieters/SO-userscripts/actions/runs/1768734016) made a connection to `gheus21ubt20eus26diag.blob.core.windows.net` during the post-complete step, as the provisioner tried to upload some artefact. The harden-runner blocked this as the host was not whitelisted.

I fully realise that just whitelisting `*.blob.core.windows.net` is not a great idea either; there could be any number of malicious payloads lurking in Azure blob stores, so ideally there should be a way to whitelist _just the known GitHub artefact and cache hosts_. This may require petitioning GitHub to use dedicated hostnames for their cache / artefact hosts and / or the use of SSL certificates on those hosts that can be verified.

**Comment by varunsh-coder** [comment]
Thanks @mjpieters for creating the issue! I agree with you. In fact I have created an [issue](https://github.com/actions/toolkit/issues/978) at `actions/toolkit` to make the artifact endpoint location available during a run, so `harden-runner` does not need to ask developer for it. This cache location issue definitely needs to be addressed in a better way. 

Do want to clarify that the `gheus21ubt20eus26diag.blob.core.windows.net` is not used for cache. In your run, the call to cache was not blocked. If you look at the `lint` job in the [run](https://app.stepsecurity.io/github/mjpieters/SO-userscripts/actions/runs/1768734016), the call is made to cache. 

`gheus21ubt20eus26diag.blob.core.windows.net` is used for some diagnostics after the job is finished. I had reached out to GitHub about it, and will follow up on it. But that does not affect the workflow at all.

**Comment by mjpieters** [comment]
Yes, I had seen that `gheus21ubt20eus26diag` is only accessed after run completion. But, since the logs I can access do not cover that stage, I can't verify what is being uploaded.

**Comment by varunsh-coder** [comment]
Hi @sethmoo, I observed that you used `harden-runner` in https://github.com/google/identity-credential/blob/master/.github/workflows/unit-test.yml and refer to this issue in the workflow file. 

I want to clarify that fixing this issue is not a blocker to using the `block` mode. What happened in your case was that the cache endpoint `mp1yacprodeus1file3.blob.core.windows.net` was from your fork of the repo. Whereas the one that got blocked `si05acprodeus1file1.blob.core.windows.net` is the cache endpoint for the parent repo `https://github.com/google/identity-credential`. So, if you just add the endpoint `si05acprodeus1file1.blob.core.windows.net:443` to the allowed-list, and change to `block` mode, it should run fine. 

The cache endpoint is different for a fork relative to the parent repo. If you had run the `audit` mode in a branch of the same repo, it should have worked fine. 

There are multiple workflows that are using `block` mode with the cache endpoint specified. Here is an example:
https://github.com/ben-manes/caffeine/blob/27bc594262ada030f76d668e7fc8e72e91defa4a/.github/workflows/build.yml#L9

So, while I would love to fix this issue, and hope to do that once the cache endpoint is known, it is not a blocker to using the `block` mode. I will add this info to the README file. 

Also, if you have feedback on the README or developer experience of using the `harden-runner` Action, please do share. Thanks!

**Comment by sethmoo** [comment]
Thanks!

Our workflow doesn't handle any sensitive info, and is never used to publish anything (it's only for continuous integration/tests). I'd rather not have to worry about playing whack-a-mole in case the CDN decides to change a hostname on us. Thus, I think I'll just stick with audit for now. The best fix, if we really wanted an allow list, would probably be to host the binaries we need at a well-known location. Adding wildcards to the hostnames is probably not the best solution.

In terms of feedback, `harden-runner` has been really nice to use. It came recommended to me by a coworker and I was delighted with how quickly I could integrate it into our workflow.

**Comment by varunsh-coder** [comment]
This issue is fixed in the latest release. Harden runner now auto detects the cache endpoint. 
More details in this blog post: https://blog.stepsecurity.io/harden-runner-github-action-now-auto-detects-cache-endpoints-1ad77fe2da0a

I will go ahead and close this issue. Please reopen if you think it is not working as expected. Thanks!
